apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  namespace: advanced-design-qa
  name: advanceddesign-qa-backend-config
spec:
  timeoutSec: 630
  connectionDraining:
    drainingTimeoutSec: 630
spec:
  securityPolicy:
    name: "ad-qa-cloud-armor"
