"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.originCoords = exports.SET_SELECT_MODE = exports.SET_DRAGGING = exports.TOGGLE_MAGNET_MODE = exports.SET_DELETE_DRAGGABLE_POINT_MODE = exports.SET_MOUSE_POSITION = exports.SET_NEW_DRAGGABLE_POINT_MODE = exports.DECREMENT_TOTAL_SHAPES = exports.INCREMENT_TOTAL_SHAPES = exports.SET_CANVAS_ORIGIN = exports.NORMALIZE_ZOOM = exports.DECREASE_ZOOM = exports.INCREASE_ZOOM = exports.DESELECT_SHAPE = exports.SELECT_SHAPE = void 0;
var SELECT_SHAPE = 'SELECT_SHAPE';
exports.SELECT_SHAPE = SELECT_SHAPE;
var DESELECT_SHAPE = 'DESELECT_SHAPE';
exports.DESELECT_SHAPE = DESELECT_SHAPE;
var INCREASE_ZOOM = 'INCREASE_ZOOM';
exports.INCREASE_ZOOM = INCREASE_ZOOM;
var DECREASE_ZOOM = 'DECREASE_ZOOM';
exports.DECREASE_ZOOM = DECREASE_ZOOM;
var NORMALIZE_ZOOM = 'NORMALIZE_ZOOM';
exports.NORMALIZE_ZOOM = NORMALIZE_ZOOM;
var SET_CANVAS_ORIGIN = 'SET_CANVAS_ORIGIN';
exports.SET_CANVAS_ORIGIN = SET_CANVAS_ORIGIN;
var INCREMENT_TOTAL_SHAPES = 'INCREMENT_TOTAL_SHAPES';
exports.INCREMENT_TOTAL_SHAPES = INCREMENT_TOTAL_SHAPES;
var DECREMENT_TOTAL_SHAPES = 'DECREMENT_TOTAL_SHAPES';
exports.DECREMENT_TOTAL_SHAPES = DECREMENT_TOTAL_SHAPES;
var SET_NEW_DRAGGABLE_POINT_MODE = 'SET_NEW_DRAGGABLE_POINT_MODE';
exports.SET_NEW_DRAGGABLE_POINT_MODE = SET_NEW_DRAGGABLE_POINT_MODE;
var SET_MOUSE_POSITION = 'SET_MOUSE_POSITION';
exports.SET_MOUSE_POSITION = SET_MOUSE_POSITION;
var SET_DELETE_DRAGGABLE_POINT_MODE = 'SET_DELETE_DRAGGABLE_POINT_MODE';
exports.SET_DELETE_DRAGGABLE_POINT_MODE = SET_DELETE_DRAGGABLE_POINT_MODE;
var TOGGLE_MAGNET_MODE = 'TOGGLE_MAGNET_MODE';
exports.TOGGLE_MAGNET_MODE = TOGGLE_MAGNET_MODE;
var SET_DRAGGING = 'SET_DRAGGING';
exports.SET_DRAGGING = SET_DRAGGING;
var SET_SELECT_MODE = 'SET_SELECT_MODE';
exports.SET_SELECT_MODE = SET_SELECT_MODE;
var originCoords = 20;
exports.originCoords = originCoords;