"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.RESET_PRODUCTION_VALUE = exports.INCREASE_PRODUCTION_VALUE = exports.DECREASE_PRODUCTION_VALUE = exports.CANCEL_PRE_LOADING = exports.SET_PRE_LOADING = exports.SET_WINDOW_DIMENSION = exports.SET_DELETE_DIALOG_PARAMS = exports.FETCHED_MODULE_SPECS = void 0;
var FETCHED_MODULE_SPECS = 'FETCHED_MODULE_SPECS';
exports.FETCHED_MODULE_SPECS = FETCHED_MODULE_SPECS;
var SET_DELETE_DIALOG_PARAMS = 'SET_DELETE_DIALOG_PARAMS';
exports.SET_DELETE_DIALOG_PARAMS = SET_DELETE_DIALOG_PARAMS;
var SET_WINDOW_DIMENSION = 'SET_WINDOW_DIMENSION';
exports.SET_WINDOW_DIMENSION = SET_WINDOW_DIMENSION;
var SET_PRE_LOADING = 'SET_PRE_LOADING';
exports.SET_PRE_LOADING = SET_PRE_LOADING;
var CANCEL_PRE_LOADING = 'CANCEL_PRE_LOADING';
exports.CANCEL_PRE_LOADING = CANCEL_PRE_LOADING;
var DECREASE_PRODUCTION_VALUE = 'DECREASE_PRODUCTION_VALUE';
exports.DECREASE_PRODUCTION_VALUE = DECREASE_PRODUCTION_VALUE;
var INCREASE_PRODUCTION_VALUE = 'INCREASE_PRODUCTION_VALUE';
exports.INCREASE_PRODUCTION_VALUE = INCREASE_PRODUCTION_VALUE;
var RESET_PRODUCTION_VALUE = 'RESET_PRODUCTION_VALUE';
exports.RESET_PRODUCTION_VALUE = RESET_PRODUCTION_VALUE;